version: '3.8'
services:
  frontend:
    image: ghcr.io/jhaworth21/hacksheffield-9/frontend:latest
    ports:
      - "6002:80"

  backend:
    image: ghcr.io/jhaworth21/hacksheffield-9/backend:latest
    ports:
        - "6001:3000"
    env_file:
      - .backend.secrets.env
    environment:
      - DEPLOYED=true
